apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: reverse-words
spec:
  host: 
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: reverse-words
    weight: 100
status:
  ingress: []
